### PR TITLE
Deposit contract

### PR DESCRIPTION
**Pull request by jaystyles**
0xAed9FC9638f7d76C9F003B11A9798c21486D9a9b

### CODE REVIEW

**Comment by dapplion** [comment]
Please justify this change

**Comment by arnetheduck** [comment]
Similar to https://github.com/eth2-clients/eth2-networks/pull/62, on the off chance that you're genuine: you've ended up in the wrong project here: in that conversation, we've recommended some resources to get up to speed with how to work with git and github - do take a moment to read these.

In the meantime, I'm removing the hex number in the PR description, lest it be confused with an ethereum address.

**Review by jaystyles — COMMENTED** [review]
Mr.F

**Review by jaystyles — COMMENTED** [review]
Thatworks

**Comment by jaystyles** [comment]
It's. My node

**Pull request closed without merging**
