### PR TITLE
Etherum

### PR DESCRIPTION
**Pull request by jaystyles**

### CODE REVIEW

**Comment by AgeManning** [comment]
haha, nice attempt tho :)

**Comment by jaystyles** [comment]
> haha, nice attempt tho :), also 10 points for committing to "Etherum"

Ok I’m stuck don’t know where to go from my project I’m stuck can u help

**Comment by jaystyles** [comment]
> Whatever your project, its likely not this repo.

My project is jaystyles

**Comment by jaystyles** [comment]
> > Whatever your project, its likely not this repo.
> 
> My project is jaystyles

Your on my fucking repo

**Comment by jaystyles** [comment]
> On the off-chance you are genuine:
> 
> If you notice the url of this page, you'll see that its github.com/eth2-clients/eth2-networks. Also the title at the top of this page is eth2-clients/eth2-networks. This is not your repository. You have forked this repository and made a pull request to it. Perhaps you mean to make a pull request to your own fork.
> 
> I'd suggest reading about how pull requests (and forks) work in github.

What does it mean by client master into the master

**Pull request closed without merging**
